version: "3"

services:
  server:
    environment:
      - PYTHONUNBUFFERED=1
    build: server/
    ports:
      - 8000:8000
    command: python3 -u ./server.py

  image-client:
    build: image-client/
    network_mode: host
    depends_on:
      - server
    command: python3 -u ./image_client.py

  label-client:
    build: label-client/
    network_mode: host
    depends_on:
      - server
    command: python3 -u ./label_client.py
